### PR TITLE
Model/Dataset FQN

### LINKED ISSUE #72: Configure dataset and net via FQN instead of module/class
[cxMNIST](Cognexa/cxMNIST) must be updated as well

### PR DESCRIPTION
**Pull request by petrbel**
- closes #72 

See also [TF](Cognexa/cxflow-tensorflow#35) and [cxMNIST](Cognexa/cxMNIST#11) PRs.

### CODE REVIEW

**Comment by FloopCZ** [comment]
Changing this to WIP, since `create_object_from_config` will be removed in later commits.

**Comment by blazekadam** [comment]
Great, its quite ugly anyways :)

**Comment by petrbel** [comment]
@FloopCZ: `create_object_from_config` removed

**Comment by FloopCZ** [comment]
Great, thanks!

**Comment by FloopCZ** [comment]
Just please use better commit names next time!

**Pull request merged**
