### PR TITLE
Removed create_[valid/test]_stream

### PR DESCRIPTION
**Pull request by gnovis**

### CODE REVIEW

**Comment by blazekadam** [comment]
This is misunderstanding. The methods should not be removed. We want to get rid of the `create_` prefix. I.e., its only a refactor. Besides the datasets, `main_loop.py` needs to be changed.

**Comment by petrbel** [comment]
btw mainloop should be updated as well, doesn't it?

**Comment by blazekadam** [comment]
I just pointed that out :)

**Comment by petrbel** [comment]
oh :D sorry

**Pull request merged**
